[2023-04-24 20:38:28,299] {{logging_mixin.py:112}} INFO - [2023-04-24 20:38:28,299] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=163
[2023-04-24 20:38:28,306] {{scheduler_job.py:153}} INFO - Started process (PID=163) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:38:28,312] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:38:28,313] {{logging_mixin.py:112}} INFO - [2023-04-24 20:38:28,313] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:38:28,325] {{logging_mixin.py:112}} INFO - [2023-04-24 20:38:28,324] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dags.dags_config import Config
ModuleNotFoundError: No module named 'dags.dags_config'
[2023-04-24 20:38:28,326] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:38:28,356] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.050 seconds
[2023-04-24 20:38:44,291] {{logging_mixin.py:112}} INFO - [2023-04-24 20:38:44,291] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=178
[2023-04-24 20:38:44,295] {{scheduler_job.py:153}} INFO - Started process (PID=178) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:38:44,299] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:38:44,300] {{logging_mixin.py:112}} INFO - [2023-04-24 20:38:44,300] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:38:44,310] {{logging_mixin.py:112}} INFO - [2023-04-24 20:38:44,308] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dags.dags_config import Config
ModuleNotFoundError: No module named 'dags.dags_config'
[2023-04-24 20:38:44,310] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:38:44,345] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.050 seconds
[2023-04-24 20:39:00,341] {{logging_mixin.py:112}} INFO - [2023-04-24 20:39:00,340] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=189
[2023-04-24 20:39:00,347] {{scheduler_job.py:153}} INFO - Started process (PID=189) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:39:00,352] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:39:00,353] {{logging_mixin.py:112}} INFO - [2023-04-24 20:39:00,353] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:39:00,362] {{logging_mixin.py:112}} INFO - [2023-04-24 20:39:00,361] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dags.dags_config import Config
ModuleNotFoundError: No module named 'dags.dags_config'
[2023-04-24 20:39:00,363] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:39:00,398] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.051 seconds
[2023-04-24 20:39:16,386] {{logging_mixin.py:112}} INFO - [2023-04-24 20:39:16,386] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=194
[2023-04-24 20:39:16,390] {{scheduler_job.py:153}} INFO - Started process (PID=194) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:39:16,394] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:39:16,394] {{logging_mixin.py:112}} INFO - [2023-04-24 20:39:16,394] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:39:16,402] {{logging_mixin.py:112}} INFO - [2023-04-24 20:39:16,401] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dags.dags_config import Config
ModuleNotFoundError: No module named 'dags.dags_config'
[2023-04-24 20:39:16,402] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:39:16,430] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.040 seconds
[2023-04-24 20:39:32,434] {{logging_mixin.py:112}} INFO - [2023-04-24 20:39:32,434] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=205
[2023-04-24 20:39:32,441] {{scheduler_job.py:153}} INFO - Started process (PID=205) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:39:32,445] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:39:32,446] {{logging_mixin.py:112}} INFO - [2023-04-24 20:39:32,445] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:39:32,455] {{logging_mixin.py:112}} INFO - [2023-04-24 20:39:32,454] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dags.dags_config import Config
ModuleNotFoundError: No module named 'dags.dags_config'
[2023-04-24 20:39:32,456] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:39:32,487] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.046 seconds
[2023-04-24 20:39:48,486] {{logging_mixin.py:112}} INFO - [2023-04-24 20:39:48,486] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=216
[2023-04-24 20:39:48,490] {{scheduler_job.py:153}} INFO - Started process (PID=216) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:39:48,493] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:39:48,493] {{logging_mixin.py:112}} INFO - [2023-04-24 20:39:48,493] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:39:48,500] {{logging_mixin.py:112}} INFO - [2023-04-24 20:39:48,499] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dags.dags_config import Config
ModuleNotFoundError: No module named 'dags.dags_config'
[2023-04-24 20:39:48,500] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:39:48,524] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.034 seconds
[2023-04-24 20:40:04,531] {{logging_mixin.py:112}} INFO - [2023-04-24 20:40:04,531] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=221
[2023-04-24 20:40:04,535] {{scheduler_job.py:153}} INFO - Started process (PID=221) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:40:04,539] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:40:04,539] {{logging_mixin.py:112}} INFO - [2023-04-24 20:40:04,539] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:40:04,547] {{logging_mixin.py:112}} INFO - [2023-04-24 20:40:04,545] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dags.dags_config import Config
ModuleNotFoundError: No module named 'dags.dags_config'
[2023-04-24 20:40:04,547] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:40:04,575] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.040 seconds
[2023-04-24 20:40:20,592] {{logging_mixin.py:112}} INFO - [2023-04-24 20:40:20,592] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=233
[2023-04-24 20:40:20,596] {{scheduler_job.py:153}} INFO - Started process (PID=233) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:40:20,599] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:40:20,599] {{logging_mixin.py:112}} INFO - [2023-04-24 20:40:20,599] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:40:20,610] {{logging_mixin.py:112}} INFO - [2023-04-24 20:40:20,605] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dags.dags_config import Config
ModuleNotFoundError: No module named 'dags.dags_config'
[2023-04-24 20:40:20,611] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:40:20,630] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.034 seconds
[2023-04-24 20:40:36,641] {{logging_mixin.py:112}} INFO - [2023-04-24 20:40:36,641] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=238
[2023-04-24 20:40:36,645] {{scheduler_job.py:153}} INFO - Started process (PID=238) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:40:36,649] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:40:36,649] {{logging_mixin.py:112}} INFO - [2023-04-24 20:40:36,649] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:40:36,662] {{logging_mixin.py:112}} INFO - [2023-04-24 20:40:36,660] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dags.dags_config import Config
ModuleNotFoundError: No module named 'dags.dags_config'
[2023-04-24 20:40:36,662] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:40:36,684] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.039 seconds
[2023-04-24 20:40:52,694] {{logging_mixin.py:112}} INFO - [2023-04-24 20:40:52,694] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=250
[2023-04-24 20:40:52,698] {{scheduler_job.py:153}} INFO - Started process (PID=250) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:40:52,701] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:40:52,702] {{logging_mixin.py:112}} INFO - [2023-04-24 20:40:52,702] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:40:52,714] {{logging_mixin.py:112}} INFO - [2023-04-24 20:40:52,713] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 20
    except Exception as err:
         ^
SyntaxError: invalid syntax
[2023-04-24 20:40:52,714] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:40:52,738] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.040 seconds
[2023-04-24 20:41:08,752] {{logging_mixin.py:112}} INFO - [2023-04-24 20:41:08,751] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=255
[2023-04-24 20:41:30,041] {{logging_mixin.py:112}} INFO - [2023-04-24 20:41:30,041] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=163
[2023-04-24 20:41:30,045] {{scheduler_job.py:153}} INFO - Started process (PID=163) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:41:30,049] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:41:30,050] {{logging_mixin.py:112}} INFO - [2023-04-24 20:41:30,050] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:41:30,058] {{logging_mixin.py:112}} INFO - [2023-04-24 20:41:30,057] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 20
    except Exception as err:
         ^
SyntaxError: invalid syntax
[2023-04-24 20:41:30,059] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:41:30,084] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.039 seconds
[2023-04-24 20:41:46,041] {{logging_mixin.py:112}} INFO - [2023-04-24 20:41:46,041] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=179
[2023-04-24 20:41:46,045] {{scheduler_job.py:153}} INFO - Started process (PID=179) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:41:46,049] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:41:46,049] {{logging_mixin.py:112}} INFO - [2023-04-24 20:41:46,049] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:41:46,056] {{logging_mixin.py:112}} INFO - [2023-04-24 20:41:46,055] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 20
    except Exception as err:
         ^
SyntaxError: invalid syntax
[2023-04-24 20:41:46,057] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:41:46,081] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.035 seconds
[2023-04-24 20:42:02,089] {{logging_mixin.py:112}} INFO - [2023-04-24 20:42:02,088] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=190
[2023-04-24 20:42:02,093] {{scheduler_job.py:153}} INFO - Started process (PID=190) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:42:02,097] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:42:02,097] {{logging_mixin.py:112}} INFO - [2023-04-24 20:42:02,097] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:42:02,105] {{logging_mixin.py:112}} INFO - [2023-04-24 20:42:02,104] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 20
    except Exception as err:
         ^
SyntaxError: invalid syntax
[2023-04-24 20:42:02,105] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:42:02,132] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.039 seconds
[2023-04-24 20:42:18,137] {{logging_mixin.py:112}} INFO - [2023-04-24 20:42:18,137] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=195
[2023-04-24 20:42:18,141] {{scheduler_job.py:153}} INFO - Started process (PID=195) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:42:18,144] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:42:18,144] {{logging_mixin.py:112}} INFO - [2023-04-24 20:42:18,144] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:42:18,151] {{logging_mixin.py:112}} INFO - [2023-04-24 20:42:18,150] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 20
    except Exception as err:
         ^
SyntaxError: invalid syntax
[2023-04-24 20:42:18,151] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:42:18,174] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.033 seconds
[2023-04-24 20:42:34,188] {{logging_mixin.py:112}} INFO - [2023-04-24 20:42:34,188] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=207
[2023-04-24 20:42:34,191] {{scheduler_job.py:153}} INFO - Started process (PID=207) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:42:34,194] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:42:34,195] {{logging_mixin.py:112}} INFO - [2023-04-24 20:42:34,195] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:42:34,201] {{logging_mixin.py:112}} INFO - [2023-04-24 20:42:34,200] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 20
    except Exception as err:
         ^
SyntaxError: invalid syntax
[2023-04-24 20:42:34,202] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:42:34,227] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.036 seconds
[2023-04-24 20:42:50,235] {{logging_mixin.py:112}} INFO - [2023-04-24 20:42:50,234] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=218
[2023-04-24 20:42:50,238] {{scheduler_job.py:153}} INFO - Started process (PID=218) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:42:50,241] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:42:50,242] {{logging_mixin.py:112}} INFO - [2023-04-24 20:42:50,241] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:42:50,248] {{logging_mixin.py:112}} INFO - [2023-04-24 20:42:50,247] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 20
    except Exception as err:
         ^
SyntaxError: invalid syntax
[2023-04-24 20:42:50,248] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:42:50,270] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.032 seconds
[2023-04-24 20:43:06,284] {{logging_mixin.py:112}} INFO - [2023-04-24 20:43:06,283] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=223
[2023-04-24 20:43:06,288] {{scheduler_job.py:153}} INFO - Started process (PID=223) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:43:06,291] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:43:06,291] {{logging_mixin.py:112}} INFO - [2023-04-24 20:43:06,291] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:43:06,299] {{logging_mixin.py:112}} INFO - [2023-04-24 20:43:06,298] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 20
    except Exception as err:
         ^
SyntaxError: invalid syntax
[2023-04-24 20:43:06,299] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:43:06,325] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.037 seconds
[2023-04-24 20:43:22,334] {{logging_mixin.py:112}} INFO - [2023-04-24 20:43:22,334] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=234
[2023-04-24 20:43:22,338] {{scheduler_job.py:153}} INFO - Started process (PID=234) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:43:22,341] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:43:22,341] {{logging_mixin.py:112}} INFO - [2023-04-24 20:43:22,341] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:43:22,352] {{logging_mixin.py:112}} INFO - [2023-04-24 20:43:22,347] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 20
    except Exception as err:
         ^
SyntaxError: invalid syntax
[2023-04-24 20:43:22,353] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:43:22,376] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.038 seconds
[2023-04-24 20:43:38,383] {{logging_mixin.py:112}} INFO - [2023-04-24 20:43:38,383] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=239
[2023-04-24 20:43:38,387] {{scheduler_job.py:153}} INFO - Started process (PID=239) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:43:38,390] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:43:38,391] {{logging_mixin.py:112}} INFO - [2023-04-24 20:43:38,391] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:43:38,402] {{logging_mixin.py:112}} INFO - [2023-04-24 20:43:38,401] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 20
    except Exception as err:
         ^
SyntaxError: invalid syntax
[2023-04-24 20:43:38,402] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:43:38,424] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.037 seconds
[2023-04-24 20:43:54,436] {{logging_mixin.py:112}} INFO - [2023-04-24 20:43:54,436] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=250
[2023-04-24 20:43:54,440] {{scheduler_job.py:153}} INFO - Started process (PID=250) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:43:54,444] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:43:54,444] {{logging_mixin.py:112}} INFO - [2023-04-24 20:43:54,444] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:43:54,456] {{logging_mixin.py:112}} INFO - [2023-04-24 20:43:54,454] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 20
    except Exception as err:
         ^
SyntaxError: invalid syntax
[2023-04-24 20:43:54,456] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:43:54,479] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.039 seconds
[2023-04-24 20:44:10,486] {{logging_mixin.py:112}} INFO - [2023-04-24 20:44:10,485] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=255
[2023-04-24 20:44:10,490] {{scheduler_job.py:153}} INFO - Started process (PID=255) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:44:10,493] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:44:10,494] {{logging_mixin.py:112}} INFO - [2023-04-24 20:44:10,494] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:44:10,505] {{logging_mixin.py:112}} INFO - [2023-04-24 20:44:10,504] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 20
    except Exception as err:
         ^
SyntaxError: invalid syntax
[2023-04-24 20:44:10,505] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:44:10,526] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.036 seconds
[2023-04-24 20:44:26,528] {{logging_mixin.py:112}} INFO - [2023-04-24 20:44:26,527] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=266
[2023-04-24 20:44:26,531] {{scheduler_job.py:153}} INFO - Started process (PID=266) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:44:26,534] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:44:26,535] {{logging_mixin.py:112}} INFO - [2023-04-24 20:44:26,535] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:44:26,545] {{logging_mixin.py:112}} INFO - [2023-04-24 20:44:26,544] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 16
    try:
       ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:44:26,545] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:44:26,564] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.032 seconds
[2023-04-24 20:44:59,678] {{logging_mixin.py:112}} INFO - [2023-04-24 20:44:59,677] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=164
[2023-04-24 20:44:59,684] {{scheduler_job.py:153}} INFO - Started process (PID=164) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:44:59,690] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:44:59,691] {{logging_mixin.py:112}} INFO - [2023-04-24 20:44:59,691] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:44:59,722] {{logging_mixin.py:112}} INFO - [2023-04-24 20:44:59,720] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 16
    try:
       ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:44:59,722] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:44:59,779] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.095 seconds
[2023-04-24 20:45:15,603] {{logging_mixin.py:112}} INFO - [2023-04-24 20:45:15,602] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=179
[2023-04-24 20:45:15,609] {{scheduler_job.py:153}} INFO - Started process (PID=179) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:45:15,614] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:45:15,615] {{logging_mixin.py:112}} INFO - [2023-04-24 20:45:15,614] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:45:15,624] {{logging_mixin.py:112}} INFO - [2023-04-24 20:45:15,622] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 16
    try:
       ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:45:15,624] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:45:15,657] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.048 seconds
[2023-04-24 20:45:30,729] {{logging_mixin.py:112}} INFO - [2023-04-24 20:45:30,729] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=191
[2023-04-24 20:45:30,733] {{scheduler_job.py:153}} INFO - Started process (PID=191) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:45:30,737] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:45:30,737] {{logging_mixin.py:112}} INFO - [2023-04-24 20:45:30,737] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:45:30,745] {{logging_mixin.py:112}} INFO - [2023-04-24 20:45:30,743] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 16
    try:
       ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:45:30,745] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:45:30,770] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.037 seconds
[2023-04-24 20:45:46,682] {{logging_mixin.py:112}} INFO - [2023-04-24 20:45:46,682] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=196
[2023-04-24 20:45:46,686] {{scheduler_job.py:153}} INFO - Started process (PID=196) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:45:46,689] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:45:46,690] {{logging_mixin.py:112}} INFO - [2023-04-24 20:45:46,690] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:45:46,696] {{logging_mixin.py:112}} INFO - [2023-04-24 20:45:46,695] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 16
    try:
       ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:45:46,697] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:45:46,722] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.036 seconds
[2023-04-24 20:46:01,808] {{logging_mixin.py:112}} INFO - [2023-04-24 20:46:01,807] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=208
[2023-04-24 20:46:01,812] {{scheduler_job.py:153}} INFO - Started process (PID=208) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:46:01,815] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:46:01,816] {{logging_mixin.py:112}} INFO - [2023-04-24 20:46:01,816] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:46:01,823] {{logging_mixin.py:112}} INFO - [2023-04-24 20:46:01,822] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 16
    try:
       ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:46:01,823] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:46:01,859] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.047 seconds
[2023-04-24 20:46:17,765] {{logging_mixin.py:112}} INFO - [2023-04-24 20:46:17,764] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=213
[2023-04-24 20:46:17,769] {{scheduler_job.py:153}} INFO - Started process (PID=213) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:46:17,772] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:46:17,773] {{logging_mixin.py:112}} INFO - [2023-04-24 20:46:17,773] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:46:17,780] {{logging_mixin.py:112}} INFO - [2023-04-24 20:46:17,779] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 16
    try:
       ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:46:17,780] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:46:17,806] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.037 seconds
[2023-04-24 20:46:32,883] {{logging_mixin.py:112}} INFO - [2023-04-24 20:46:32,882] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=224
[2023-04-24 20:46:32,887] {{scheduler_job.py:153}} INFO - Started process (PID=224) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:46:32,890] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:46:32,891] {{logging_mixin.py:112}} INFO - [2023-04-24 20:46:32,891] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:46:32,898] {{logging_mixin.py:112}} INFO - [2023-04-24 20:46:32,897] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 16
    try:
       ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:46:32,898] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:46:32,926] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.040 seconds
[2023-04-24 20:46:48,841] {{logging_mixin.py:112}} INFO - [2023-04-24 20:46:48,840] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=229
[2023-04-24 20:46:48,844] {{scheduler_job.py:153}} INFO - Started process (PID=229) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:46:48,848] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:46:48,848] {{logging_mixin.py:112}} INFO - [2023-04-24 20:46:48,848] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:46:48,855] {{logging_mixin.py:112}} INFO - [2023-04-24 20:46:48,854] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 16
    try:
       ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:46:48,855] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:46:48,884] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.039 seconds
[2023-04-24 20:47:03,946] {{logging_mixin.py:112}} INFO - [2023-04-24 20:47:03,946] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=240
[2023-04-24 20:47:03,950] {{scheduler_job.py:153}} INFO - Started process (PID=240) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:47:03,953] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:47:03,953] {{logging_mixin.py:112}} INFO - [2023-04-24 20:47:03,953] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:47:03,963] {{logging_mixin.py:112}} INFO - [2023-04-24 20:47:03,962] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 16
    try:
       ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:47:03,963] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:47:03,984] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.034 seconds
[2023-04-24 20:47:19,918] {{logging_mixin.py:112}} INFO - [2023-04-24 20:47:19,917] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=251
[2023-04-24 20:47:19,921] {{scheduler_job.py:153}} INFO - Started process (PID=251) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:47:19,924] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:47:19,924] {{logging_mixin.py:112}} INFO - [2023-04-24 20:47:19,924] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:47:19,934] {{logging_mixin.py:112}} INFO - [2023-04-24 20:47:19,933] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 16
    try:
       ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:47:19,934] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:47:19,953] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.032 seconds
[2023-04-24 20:47:35,017] {{logging_mixin.py:112}} INFO - [2023-04-24 20:47:35,016] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=256
[2023-04-24 20:47:35,021] {{scheduler_job.py:153}} INFO - Started process (PID=256) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:47:35,024] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:47:35,025] {{logging_mixin.py:112}} INFO - [2023-04-24 20:47:35,025] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:47:35,037] {{logging_mixin.py:112}} INFO - [2023-04-24 20:47:35,035] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:47:35,037] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:47:35,058] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.037 seconds
[2023-04-24 20:47:51,000] {{logging_mixin.py:112}} INFO - [2023-04-24 20:47:51,000] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=267
[2023-04-24 20:47:51,005] {{scheduler_job.py:153}} INFO - Started process (PID=267) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:47:51,008] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:47:51,009] {{logging_mixin.py:112}} INFO - [2023-04-24 20:47:51,009] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:47:51,021] {{logging_mixin.py:112}} INFO - [2023-04-24 20:47:51,020] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:47:51,021] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:47:51,050] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.045 seconds
[2023-04-24 20:48:07,049] {{logging_mixin.py:112}} INFO - [2023-04-24 20:48:07,049] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=272
[2023-04-24 20:48:07,054] {{scheduler_job.py:153}} INFO - Started process (PID=272) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:48:07,058] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:48:07,058] {{logging_mixin.py:112}} INFO - [2023-04-24 20:48:07,058] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:48:07,075] {{logging_mixin.py:112}} INFO - [2023-04-24 20:48:07,073] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:48:07,075] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:48:07,097] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.043 seconds
[2023-04-24 20:48:40,391] {{logging_mixin.py:112}} INFO - [2023-04-24 20:48:40,391] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=163
[2023-04-24 20:48:40,395] {{scheduler_job.py:153}} INFO - Started process (PID=163) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:48:40,399] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:48:40,400] {{logging_mixin.py:112}} INFO - [2023-04-24 20:48:40,400] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:48:40,408] {{logging_mixin.py:112}} INFO - [2023-04-24 20:48:40,407] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:48:40,408] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:48:40,432] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.037 seconds
[2023-04-24 20:48:56,389] {{logging_mixin.py:112}} INFO - [2023-04-24 20:48:56,389] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=179
[2023-04-24 20:48:56,393] {{scheduler_job.py:153}} INFO - Started process (PID=179) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:48:56,397] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:48:56,398] {{logging_mixin.py:112}} INFO - [2023-04-24 20:48:56,397] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:48:56,405] {{logging_mixin.py:112}} INFO - [2023-04-24 20:48:56,403] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:48:56,405] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:48:56,434] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.041 seconds
[2023-04-24 20:49:12,436] {{logging_mixin.py:112}} INFO - [2023-04-24 20:49:12,435] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=190
[2023-04-24 20:49:12,440] {{scheduler_job.py:153}} INFO - Started process (PID=190) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:49:12,443] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:49:12,444] {{logging_mixin.py:112}} INFO - [2023-04-24 20:49:12,444] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:49:12,451] {{logging_mixin.py:112}} INFO - [2023-04-24 20:49:12,450] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:49:12,451] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:49:12,476] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.036 seconds
[2023-04-24 20:49:28,485] {{logging_mixin.py:112}} INFO - [2023-04-24 20:49:28,485] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=195
[2023-04-24 20:49:28,489] {{scheduler_job.py:153}} INFO - Started process (PID=195) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:49:28,492] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:49:28,492] {{logging_mixin.py:112}} INFO - [2023-04-24 20:49:28,492] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:49:28,499] {{logging_mixin.py:112}} INFO - [2023-04-24 20:49:28,498] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:49:28,499] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:49:28,522] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.033 seconds
[2023-04-24 20:49:44,538] {{logging_mixin.py:112}} INFO - [2023-04-24 20:49:44,538] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=206
[2023-04-24 20:49:44,542] {{scheduler_job.py:153}} INFO - Started process (PID=206) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:49:44,545] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:49:44,546] {{logging_mixin.py:112}} INFO - [2023-04-24 20:49:44,546] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:49:44,553] {{logging_mixin.py:112}} INFO - [2023-04-24 20:49:44,551] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:49:44,553] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:49:44,581] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.039 seconds
[2023-04-24 20:50:00,586] {{logging_mixin.py:112}} INFO - [2023-04-24 20:50:00,586] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=217
[2023-04-24 20:50:00,590] {{scheduler_job.py:153}} INFO - Started process (PID=217) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:50:00,593] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:50:00,594] {{logging_mixin.py:112}} INFO - [2023-04-24 20:50:00,594] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:50:00,600] {{logging_mixin.py:112}} INFO - [2023-04-24 20:50:00,599] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:50:00,600] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:50:00,624] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.034 seconds
[2023-04-24 20:50:16,631] {{logging_mixin.py:112}} INFO - [2023-04-24 20:50:16,631] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=222
[2023-04-24 20:50:16,635] {{scheduler_job.py:153}} INFO - Started process (PID=222) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:50:16,637] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:50:16,638] {{logging_mixin.py:112}} INFO - [2023-04-24 20:50:16,638] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:50:16,644] {{logging_mixin.py:112}} INFO - [2023-04-24 20:50:16,643] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:50:16,644] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:50:16,666] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.031 seconds
[2023-04-24 20:50:32,681] {{logging_mixin.py:112}} INFO - [2023-04-24 20:50:32,681] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=233
[2023-04-24 20:50:32,685] {{scheduler_job.py:153}} INFO - Started process (PID=233) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:50:32,687] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:50:32,688] {{logging_mixin.py:112}} INFO - [2023-04-24 20:50:32,688] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:50:32,697] {{logging_mixin.py:112}} INFO - [2023-04-24 20:50:32,693] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:50:32,698] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:50:32,716] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.032 seconds
[2023-04-24 20:50:48,727] {{logging_mixin.py:112}} INFO - [2023-04-24 20:50:48,727] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=238
[2023-04-24 20:50:48,731] {{scheduler_job.py:153}} INFO - Started process (PID=238) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:50:48,734] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:50:48,734] {{logging_mixin.py:112}} INFO - [2023-04-24 20:50:48,734] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:50:48,744] {{logging_mixin.py:112}} INFO - [2023-04-24 20:50:48,743] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:50:48,744] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:50:48,763] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.032 seconds
[2023-04-24 20:51:04,779] {{logging_mixin.py:112}} INFO - [2023-04-24 20:51:04,779] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=249
[2023-04-24 20:51:04,783] {{scheduler_job.py:153}} INFO - Started process (PID=249) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:51:04,786] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:51:04,787] {{logging_mixin.py:112}} INFO - [2023-04-24 20:51:04,787] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:51:04,798] {{logging_mixin.py:112}} INFO - [2023-04-24 20:51:04,797] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:51:04,798] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:51:04,820] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.037 seconds
[2023-04-24 20:51:20,833] {{logging_mixin.py:112}} INFO - [2023-04-24 20:51:20,832] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=254
[2023-04-24 20:51:20,837] {{scheduler_job.py:153}} INFO - Started process (PID=254) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:51:20,840] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:51:20,841] {{logging_mixin.py:112}} INFO - [2023-04-24 20:51:20,841] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:51:20,853] {{logging_mixin.py:112}} INFO - [2023-04-24 20:51:20,851] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:51:20,853] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:51:20,874] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.037 seconds
[2023-04-24 20:51:36,878] {{logging_mixin.py:112}} INFO - [2023-04-24 20:51:36,877] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=266
[2023-04-24 20:51:36,881] {{scheduler_job.py:153}} INFO - Started process (PID=266) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:51:36,884] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:51:36,885] {{logging_mixin.py:112}} INFO - [2023-04-24 20:51:36,885] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:51:36,895] {{logging_mixin.py:112}} INFO - [2023-04-24 20:51:36,894] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:51:36,895] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:51:36,914] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.033 seconds
[2023-04-24 20:51:52,929] {{logging_mixin.py:112}} INFO - [2023-04-24 20:51:52,929] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=271
[2023-04-24 20:51:52,933] {{scheduler_job.py:153}} INFO - Started process (PID=271) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:51:52,936] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:51:52,936] {{logging_mixin.py:112}} INFO - [2023-04-24 20:51:52,936] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:51:52,946] {{logging_mixin.py:112}} INFO - [2023-04-24 20:51:52,945] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:51:52,946] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:51:52,968] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.036 seconds
[2023-04-24 20:52:08,973] {{logging_mixin.py:112}} INFO - [2023-04-24 20:52:08,973] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=282
[2023-04-24 20:52:08,977] {{scheduler_job.py:153}} INFO - Started process (PID=282) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:52:08,979] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:52:08,980] {{logging_mixin.py:112}} INFO - [2023-04-24 20:52:08,980] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:52:08,990] {{logging_mixin.py:112}} INFO - [2023-04-24 20:52:08,989] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:52:08,990] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:52:09,009] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.033 seconds
[2023-04-24 20:52:25,023] {{logging_mixin.py:112}} INFO - [2023-04-24 20:52:25,023] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=287
[2023-04-24 20:52:25,028] {{scheduler_job.py:153}} INFO - Started process (PID=287) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:52:25,031] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:52:25,032] {{logging_mixin.py:112}} INFO - [2023-04-24 20:52:25,032] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:52:25,045] {{logging_mixin.py:112}} INFO - [2023-04-24 20:52:25,044] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:52:25,045] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:52:25,065] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.038 seconds
[2023-04-24 20:52:41,074] {{logging_mixin.py:112}} INFO - [2023-04-24 20:52:41,074] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=298
[2023-04-24 20:52:41,077] {{scheduler_job.py:153}} INFO - Started process (PID=298) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:52:41,083] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:52:41,084] {{logging_mixin.py:112}} INFO - [2023-04-24 20:52:41,084] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:52:41,090] {{logging_mixin.py:112}} INFO - [2023-04-24 20:52:41,089] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:52:41,090] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:52:41,108] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.031 seconds
[2023-04-24 20:52:57,127] {{logging_mixin.py:112}} INFO - [2023-04-24 20:52:57,126] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=303
[2023-04-24 20:52:57,131] {{scheduler_job.py:153}} INFO - Started process (PID=303) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:52:57,139] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:52:57,139] {{logging_mixin.py:112}} INFO - [2023-04-24 20:52:57,139] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:52:57,146] {{logging_mixin.py:112}} INFO - [2023-04-24 20:52:57,145] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:52:57,146] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:52:57,169] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.038 seconds
[2023-04-24 20:53:13,176] {{logging_mixin.py:112}} INFO - [2023-04-24 20:53:13,176] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=314
[2023-04-24 20:53:13,180] {{scheduler_job.py:153}} INFO - Started process (PID=314) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:53:13,187] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:53:13,187] {{logging_mixin.py:112}} INFO - [2023-04-24 20:53:13,187] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:53:13,194] {{logging_mixin.py:112}} INFO - [2023-04-24 20:53:13,192] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:53:13,194] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:53:13,213] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.033 seconds
[2023-04-24 20:53:29,218] {{logging_mixin.py:112}} INFO - [2023-04-24 20:53:29,218] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=319
[2023-04-24 20:53:29,222] {{scheduler_job.py:153}} INFO - Started process (PID=319) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:53:29,228] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:53:29,228] {{logging_mixin.py:112}} INFO - [2023-04-24 20:53:29,228] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:53:29,234] {{logging_mixin.py:112}} INFO - [2023-04-24 20:53:29,233] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:53:29,235] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:53:29,253] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.031 seconds
[2023-04-24 20:53:45,279] {{logging_mixin.py:112}} INFO - [2023-04-24 20:53:45,279] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=330
[2023-04-24 20:53:45,283] {{scheduler_job.py:153}} INFO - Started process (PID=330) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:53:45,287] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:53:45,287] {{logging_mixin.py:112}} INFO - [2023-04-24 20:53:45,287] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:53:45,294] {{logging_mixin.py:112}} INFO - [2023-04-24 20:53:45,293] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:53:45,295] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:53:45,317] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.034 seconds
[2023-04-24 20:54:01,331] {{logging_mixin.py:112}} INFO - [2023-04-24 20:54:01,331] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=335
[2023-04-24 20:54:01,336] {{scheduler_job.py:153}} INFO - Started process (PID=335) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:54:01,339] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:54:01,340] {{logging_mixin.py:112}} INFO - [2023-04-24 20:54:01,339] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:54:01,347] {{logging_mixin.py:112}} INFO - [2023-04-24 20:54:01,346] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:54:01,347] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:54:01,370] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.034 seconds
[2023-04-24 20:54:17,379] {{logging_mixin.py:112}} INFO - [2023-04-24 20:54:17,379] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=346
[2023-04-24 20:54:17,383] {{scheduler_job.py:153}} INFO - Started process (PID=346) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:54:17,387] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:54:17,387] {{logging_mixin.py:112}} INFO - [2023-04-24 20:54:17,387] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:54:17,395] {{logging_mixin.py:112}} INFO - [2023-04-24 20:54:17,394] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:54:17,395] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:54:17,418] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.034 seconds
[2023-04-24 20:54:33,430] {{logging_mixin.py:112}} INFO - [2023-04-24 20:54:33,430] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=357
[2023-04-24 20:54:33,434] {{scheduler_job.py:153}} INFO - Started process (PID=357) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:54:33,437] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:54:33,437] {{logging_mixin.py:112}} INFO - [2023-04-24 20:54:33,437] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:54:33,443] {{logging_mixin.py:112}} INFO - [2023-04-24 20:54:33,442] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:54:33,444] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:54:33,463] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.029 seconds
[2023-04-24 20:54:49,476] {{logging_mixin.py:112}} INFO - [2023-04-24 20:54:49,475] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=362
[2023-04-24 20:54:49,479] {{scheduler_job.py:153}} INFO - Started process (PID=362) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:54:49,482] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:54:49,483] {{logging_mixin.py:112}} INFO - [2023-04-24 20:54:49,483] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:54:49,489] {{logging_mixin.py:112}} INFO - [2023-04-24 20:54:49,488] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:54:49,489] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:54:49,508] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.028 seconds
[2023-04-24 20:55:05,531] {{logging_mixin.py:112}} INFO - [2023-04-24 20:55:05,530] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=373
[2023-04-24 20:55:05,535] {{scheduler_job.py:153}} INFO - Started process (PID=373) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:55:05,538] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:55:05,539] {{logging_mixin.py:112}} INFO - [2023-04-24 20:55:05,539] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:55:05,546] {{logging_mixin.py:112}} INFO - [2023-04-24 20:55:05,545] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:55:05,546] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:55:05,570] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.035 seconds
[2023-04-24 20:55:21,584] {{logging_mixin.py:112}} INFO - [2023-04-24 20:55:21,584] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=378
[2023-04-24 20:55:21,588] {{scheduler_job.py:153}} INFO - Started process (PID=378) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:55:21,591] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:55:21,592] {{logging_mixin.py:112}} INFO - [2023-04-24 20:55:21,592] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:55:21,599] {{logging_mixin.py:112}} INFO - [2023-04-24 20:55:21,598] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:55:21,600] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:55:21,623] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.035 seconds
[2023-04-24 20:55:37,631] {{logging_mixin.py:112}} INFO - [2023-04-24 20:55:37,631] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=390
[2023-04-24 20:55:37,635] {{scheduler_job.py:153}} INFO - Started process (PID=390) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:55:37,639] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:55:37,639] {{logging_mixin.py:112}} INFO - [2023-04-24 20:55:37,639] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:55:37,647] {{logging_mixin.py:112}} INFO - [2023-04-24 20:55:37,645] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:55:37,647] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:55:37,669] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.034 seconds
[2023-04-24 20:55:53,682] {{logging_mixin.py:112}} INFO - [2023-04-24 20:55:53,681] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=395
[2023-04-24 20:55:53,685] {{scheduler_job.py:153}} INFO - Started process (PID=395) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:55:53,688] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:55:53,689] {{logging_mixin.py:112}} INFO - [2023-04-24 20:55:53,689] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:55:53,696] {{logging_mixin.py:112}} INFO - [2023-04-24 20:55:53,695] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:55:53,696] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:55:53,716] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.031 seconds
[2023-04-24 20:56:09,726] {{logging_mixin.py:112}} INFO - [2023-04-24 20:56:09,725] {{settings.py:253}} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=406
[2023-04-24 20:56:09,730] {{scheduler_job.py:153}} INFO - Started process (PID=406) to work on /usr/local/airflow/dags/dag1.py
[2023-04-24 20:56:09,733] {{scheduler_job.py:1560}} INFO - Processing file /usr/local/airflow/dags/dag1.py for tasks to queue
[2023-04-24 20:56:09,733] {{logging_mixin.py:112}} INFO - [2023-04-24 20:56:09,733] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:56:09,740] {{logging_mixin.py:112}} INFO - [2023-04-24 20:56:09,739] {{dagbag.py:246}} ERROR - Failed to import: /usr/local/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 243, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/airflow/dags/dag1.py", line 5, in <module>
    from dag1_operator import (
  File "/usr/local/airflow/dags/dag1_operator.py", line 15
    print("ingreso")
                   ^
TabError: inconsistent use of tabs and spaces in indentation
[2023-04-24 20:56:09,741] {{scheduler_job.py:1574}} WARNING - No viable dags retrieved from /usr/local/airflow/dags/dag1.py
[2023-04-24 20:56:09,760] {{scheduler_job.py:161}} INFO - Processing /usr/local/airflow/dags/dag1.py took 0.030 seconds
