version: "3.7"
networks:
  default:
    external:
      name: osv-proxy_osv_network
volumes:
  local_db_scheduler_data: {}
  local_db_scheduler_data_backups: {}

services:

  db_scheduler:
    container_name: osv_scheduler_db
    image: postgres:9.6
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - local_db_scheduler_data:/var/lib/postgresql/data
      - local_db_scheduler_data_backups:/backups
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"

  airflow:
    container_name: osv_scheduler
    image: osv_scheduler_airflow
    build:
      context: ./../
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=postgres
      - AIRFLOW=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"
    command: [ "webserver" ]
    ports:
      - "8080:8080"
    volumes:
      - ./../config/airflow.cfg:/usr/local/airflow/airflow.cfg
      - ./../config/create_default_user.py:/usr/local/airflow/create_default_user.py
      - ./../dags:/usr/local/airflow/dags
      - ./../modules:/usr/local/airflow/modules
      - ./../logs:/usr/local/airflow/logs
      - ./../downloads/:/home/seluser/Downloads
    healthcheck:
      test: [ "CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]" ]
      interval: 30s
      timeout: 30s
      retries: 3
    depends_on:
      - db_scheduler
